site_name: Complete Guide to IBS574
repo_url: https://github.com/IBS574/docs
pages:
    - [index.md, 'Home']
    - [setup.md, 'Getting Setup']
#    - [unix/commands.md, 'Unix', 'Commands']
    - [git/setup.md, 'Git', 'Setup']
    - [git/commands.md, 'Git', 'Commands']
    - [git/pull-requests.md, 'Git', 'Pull Requests']
    - [git/tutorial.md, 'Git', 'Tutorials']
#    - [python/intro.md, 'Python', 'Introduction']
#    - [python/examples.md, 'Python', 'Examples']
theme: readthedocs
theme_dir: 'custom_theme'
